server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 🔥 FIXED PRODUCT ROUTE
    location /api/products {
        proxy_pass http://productservice:5001/api/products;
    }

    # 🔥 FIXED ORDER ROUTE
    location /api/orders {
        proxy_pass http://orderservice:5002/api/orders;
    }
}
